permalink: /:title
pygments: true
exclude: [CNAME, README.md]

authors:
  matt:
    display_name: Matt Hackett
    gravatar: 60fd5218fff6927c0ed376cce01c5460
    email: matt@lostdecadegames.com
    twitter: richtaur
    github: richtaur
  geoff:
    display_name: Geoff Blair
    gravatar: 76dbcc74021b8039f14c7b583978b56d
    email: geoff@lostdecadegames.com
    twitter: geoffblair
    github: geoffb

# Local server
auto: true
server: true
server_port: 4000
